parameters:
- name: UserName
  type: string
  default: 'World'  # Default value if not provided by the user

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: HelloWorldJob
  displayName: 'Print Hello World'
  steps:
  - script: echo "Hello $(UserName)! Build ID $(Build.BuildId)"
    displayName: 'Print Hello World'
